version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  percyCSS: ""
discovery:
  allowedHostnames: []
  networkIdleTimeout: 100
static:
  include: ['**/*.{html,htm}']
  exclude: ['/event/20{08,09,10,11,12,13,14,15,16,17,18,19,20,21,22}/**','/event/2023/{toronto,huron,ottawa}/**']
