ignore:
  - "docs/**/*"
  - "**/*.gql"
  - "*.gql"
  - "gatsby-*.js"
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    branch:
      default:
        target: 50%
        threshold: 2%
