name: Database
on:
  schedule:
    - cron: '*/30 6-23 * * *'
jobs:
  wake:
    name: Wake up database engine
    runs-on: ubuntu-latest
    steps:
      - name: Good morning!
        env:
          DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
        run: curl -I ${DB_ENDPOINT}
  import:
    name: Nightly event import
    runs-on: ubuntu-latest
    steps:
      - name: Grab some events
          DB_ENDPOINT: ${{ secrets.IMPORT_ENDPOINT }}
        run: curl -X POST -I ${IMPORT_ENDPOINT}
